### ISSUE TITLE
Exception handling in plugin initialization

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/appbase#14]
https://github.com/AntelopeIO/appbase/blob/fe1e8ae173a263ea89ecd3c77a7940a3981ccb07/application_base.cpp#L402

if plugin initialization throws an error, appbase just prints "Failed to initialize" without any details. It needs a better error handling, like

```
   } catch ( const boost::exception& e ) {
    std::cerr << boost::diagnostic_information(e) << "\n";
    return false;
  } catch ( const std::exception& e ) {
    std::cerr << e.what() << "\n";
    return false;
   } catch (...) {
      std::cerr << "Failed to initialize\n";
      return false;
   }
```

How I found it: while developing a new Chronicle plugin, I tried to use a "required()" property for an option, and it appeared to throw an exception if the option was missing:

```
    (SCYLLA_HOST_OPT, bpo::value<string>()->required(), "ScyllaDB server host")
```

After adding the above code, I got the output:
```
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::wrapexcept<boost::program_options::required_option>
std::exception::what: the option '--scylla-host' is required but missing
```

Ideally, appbase needs also a proper handling of "required()" property for an option.

**Comment by greg7mdp** [comment]
@cc32d9 thanks for the issue and the fix suggestion.
